# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Pods for kovu
target 'kovu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'DoubleConversion', podspec: "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', podspec: "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', podspec: "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge', 
    'DevSupport', 
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'AppCenter'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  
  # Use the following line to use App Center Analytics and Crashes.
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  platform :ios, '9.0'
  target 'kovuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kovu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kovu-tvOS

  target 'kovu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end