# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kovu' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kovu
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'RCTLinkingIOS',
    'RCTImage'
  ]

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-camera-kit', :path => '../node_modules/react-native-camera-kit'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'kovuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kovu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kovu-tvOS

  target 'kovu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
